Feature/delivery tracking
enriqueSFranco/stock-control-system pull request #1
Opened 2024-07-04 19:31 UTC by enriqueSFranco

**Tabla de seguimiento de los pedidos**

- [x] Renderizado con propiedades dinámicas
- [x] Componetización del componente padre en (TableRow y TableCell)

**Nota: El objeto que se envié como entrada para el renderizado del seguimiento de pedidos debe tener una propiedad "estado".**

2024-07-08 22:45 UTC, Maskla-Dev commented on src/components/atoms/my-badge.css.js
Okay

2024-07-08 22:45 UTC, Maskla-Dev commented on src/components/atoms/table-content.js
ok

2024-07-08 22:45 UTC, Maskla-Dev commented on src/components/atoms/table-head.js
ok

2024-07-08 22:46 UTC, Maskla-Dev commented on src/components/molecules/delivery-datatable.css.js
ok

2024-07-08 22:46 UTC, Maskla-Dev commented on src/components/molecules/delivery-datatable.js
ok

2024-07-08 22:46 UTC, Maskla-Dev commented on src/utils/format_money.js
ok

2024-07-08 22:47 UTC, Maskla-Dev commented on src/components/pages/delivery-tracking.js
Este componente no se esta usando

2024-07-08 22:50 UTC, Maskla-Dev commented on src/my-element.js
Mover el componente a la sección templates y manda a llamar al componente desde RouteTracking de la siguiente manera
```javascript
render(){
        return html`
            <bbva-template>
               <my-element></my-element>
            </bbva-template>
        `;
    }
```

2024-07-08 22:51 UTC, Maskla-Dev requested changes
`my-element` debe de ser llamado desde la página correspondiente, moverlo a la sección templates y resolver las dependencias

2024-07-09 22:28 UTC, enriqueSFranco commented on src/my-element.js
ok

2024-07-09 22:29 UTC, enriqueSFranco commented on src/components/pages/delivery-tracking.js
Ahi pensaba poner el contenido del seguimiento de los viajes, solo hice el esqueleto pero vi que ya lo habian implementado y se me olvido eliminarlo.

2024-07-09 22:31 UTC, merged